# Generated by Django 4.2.26 on 2025-11-06 17:26

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=files.models.file_upload_path
                    ),
                ),
                ("original_filename", models.CharField(db_index=True, max_length=255)),
                ("file_type", models.CharField(db_index=True, max_length=100)),
                ("size", models.BigIntegerField(db_index=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("reference_count", models.IntegerField(default=1)),
                ("is_duplicate", models.BooleanField(default=False)),
                (
                    "original_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicates",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["file_hash", "is_duplicate"],
                        name="files_file_file_ha_bd8e27_idx",
                    )
                ],
            },
        ),
    ]
