# Generated by Django 4.2.26 on 2025-11-07 20:01

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, help_text='Physical file storage (null for duplicates)', null=True, upload_to=files.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of file content', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(db_index=True, help_text='MIME type of the file', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='True if this is a reference to another file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_file',
            field=models.ForeignKey(blank=True, help_text='Reference to original file if this is a duplicate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='files.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_filename',
            field=models.CharField(db_index=True, help_text='Original name of uploaded file', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='reference_count',
            field=models.IntegerField(default=1, help_text='Number of references to this file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(db_index=True, help_text='File size in bytes'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_at', 'is_duplicate'], name='files_file_uploade_19177b_idx'),
        ),
    ]
